name: Test for Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2.0.3
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.1

        #      - name: submodule
        #        run: git submodule update --init --recursive

        # Check the format of code
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.3

      - name: CodeCov
        run: |
          go test ./... -coverprofile=coverage.txt -covermode=atomic
          if [ -f coverage.txt ]; then
              bash <(curl -s https://codecov.io/bash)
          fi
